<?php
namespace Salesforce\ORM\Constants;

use Salesforce\Constants\Constants;

class BulkApiConstants extends Constants
{
    CONST CREATE_JOB_ACTION_INSERT = 'insert';
    CONST CREATE_JOB_ACTION_UPDATE = 'update';
    CONST CREATE_JOB_ACTION_UPSERT = 'upsert';
    CONST CREATE_JOB_ID = 'id';

    CONST JOB_FIELD_LABEL_STATE = 'state';
    CONST JOB_FIELD_VALUE_JOB_UPLOAD_COMPLETE = 'UploadComplete';
    CONST JOB_FIELD_VALUE_JOB_PROCESS_COMPLETE = 'JobComplete';

    CONST JOB_RESULT_SUCCESSFUL = 'successfulResults';
    CONST JOB_RESULT_FAILED = 'failedResults';
    CONST JOB_RESULT_UNPROCESSED = 'unprocessedRecords';

    CONST JOB_INGEST_ENDPOINT = 'ingest/';
    CONST JOB_ADD_BATCHES_ENDPOINT = 'batches/';

    CONST JOB_RESULT_PASSED_RESULT_ENDPOINT = SELF::JOB_RESULT_SUCCESSFUL . '/';
    CONST JOB_RESULT_FAIELD_RESULT_ENDPOINT = SELF::JOB_RESULT_FAILED . '/';
    CONST JOB_RESULT_UNPROCESSED_RESULT_ENDPOINT = SELF::JOB_RESULT_UNPROCESSED . '/';

    CONST GET_RESULT_RETRY = 10;
}
